[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
itertools = "0.13.0"
openpyxl = "0.1.0"
polars = {version = "0.45.1", features = ["lazy"]}
polars-io = "0.45.1"
tokio = { version = "1.42.0", features = ["full"] }
tokio-postgres = "0.7.12"
